export const conjugations = {
  past: {
    yap: {
      1: "yaptım",
      2: "yaptın",
      3: "yaptı",
      11: "yaptık",
      12: "yaptınız",
      13: "yaptılar",
    },
    ver: {
      1: "verdim",
      2: "verdin",
      3: "verdi",
      11: "verdik",
      12: "verdiniz",
      13: "verdiler",
    },
    dur: {
      1: "durdum",
      2: "durdun",
      3: "durdu",
      11: "durduk",
      12: "durdunuz",
      13: "durdular",
    },
    bak: {
      1: "baktım",
      2: "baktın",
      3: "baktı",
      11: "baktık",
      12: "baktınız",
      13: "baktılar",
    },
    gör: {
      1: "gördüm",
      2: "gördün",
      3: "gördü",
      11: "gördük",
      12: "gördünüz",
      13: "gördüler",
    },
    al: {
      1: "aldım",
      2: "aldın",
      3: "aldı",
      11: "aldık",
      12: "aldınız",
      13: "aldılar",
    },
    sev: {
      1: "sevdim",
      2: "sevdin",
      3: "sevdi",
      11: "sevdik",
      12: "sevdiniz",
      13: "sevdiler",
    },
    geç: {
      1: "geçtim",
      2: "geçtin",
      3: "geçti",
      11: "geçtik",
      12: "geçtiniz",
      13: "geçtiler",
    },
    bil: {
      1: "bildim",
      2: "bildin",
      3: "bildi",
      11: "bildik",
      12: "bildiniz",
      13: "bildiler",
    },
    söyle: {
      1: "söyledim",
      2: "söyledin",
      3: "söyledi",
      11: "söyledik",
      12: "söylediniz",
      13: "söylediler",
    },
    başla: {
      1: "başladım",
      2: "başladın",
      3: "başladı",
      11: "başladık",
      12: "başladınız",
      13: "başladılar",
    },
    düşün: {
      1: "düşündüm",
      2: "düşündün",
      3: "düşündü",
      11: "düşündük",
      12: "düşündünüz",
      13: "düşündüler",
    },
    oku: {
      1: "okudum",
      2: "okudun",
      3: "okudu",
      11: "okuduk",
      12: "okudunuz",
      13: "okudular",
    },
    bul: {
      1: "buldum",
      2: "buldun",
      3: "buldu",
      11: "bulduk",
      12: "buldunuz",
      13: "buldular",
    },
    çık: {
      1: "çıktım",
      2: "çıktın",
      3: "çıktı",
      11: "çıktık",
      12: "çıktınız",
      13: "çıktılar",
    },
  },
  pastV2: {
    yap: {
      1: "yapmışım",
      2: "yapmışsın",
      3: "yapmış",
      11: "yapmışız",
      12: "yapmışsınız",
      13: "yapmışlar",
    },
    ver: {
      1: "vermişim",
      2: "vermişsin",
      3: "vermiş",
      11: "vermişiz",
      12: "vermişsiniz",
      13: "vermişler",
    },
    dur: {
      1: "durmuşum",
      2: "durmuşsun",
      3: "durmuş",
      11: "durmuşuz",
      12: "durmuşsunuz",
      13: "durmuşlar",
    },
    bak: {
      1: "bakmışım",
      2: "bakmışsın",
      3: "bakmış",
      11: "bakmışız",
      12: "bakmışsınız",
      13: "bakmışlar",
    },
    gör: {
      1: "görmüşüm",
      2: "görmüşsün",
      3: "görmüş",
      11: "görmüşüz",
      12: "görmüşsünüz",
      13: "görmüşler",
    },
    al: {
      1: "almışım",
      2: "almışsın",
      3: "almış",
      11: "almışız",
      12: "almışsınız",
      13: "almışlar",
    },
    sev: {
      1: "sevmişim",
      2: "sevmişsin",
      3: "sevmiş",
      11: "sevmişiz",
      12: "sevmişsiniz",
      13: "sevmişler",
    },
    geç: {
      1: "geçmişim",
      2: "geçmişsin",
      3: "geçmiş",
      11: "geçmişiz",
      12: "geçmişsiniz",
      13: "geçmişler",
    },
    bil: {
      1: "bilmişim",
      2: "bilmişsin",
      3: "bilmiş",
      11: "bilmişiz",
      12: "bilmişsiniz",
      13: "bilmişler",
    },
    söyle: {
      1: "söylemişim",
      2: "söylemişsin",
      3: "söylemiş",
      11: "söylemişiz",
      12: "söylemişsiniz",
      13: "söylemişler",
    },
    başla: {
      1: "başlamışım",
      2: "başlamışsın",
      3: "başlamış",
      11: "başlamışız",
      12: "başlamışsınız",
      13: "başlamışlar",
    },
    düşün: {
      1: "düşünmüşüm",
      2: "düşünmüşsün",
      3: "düşünmüş",
      11: "düşünmüşüz",
      12: "düşünmüşsünüz",
      13: "düşünmüşler",
    },
    oku: {
      1: "okumuşum",
      2: "okumuşsun",
      3: "okumuş",
      11: "okumuşuz",
      12: "okumuşsunuz",
      13: "okumuşlar",
    },
    bul: {
      1: "bulmuşum",
      2: "bulmuşsun",
      3: "bulmuş",
      11: "bulmuşuz",
      12: "bulmuşsunuz",
      13: "bulmuşlar",
    },
    çık: {
      1: "çıkmışım",
      2: "çıkmışsın",
      3: "çıkmış",
      11: "çıkmışız",
      12: "çıkmışsınız",
      13: "çıkmışlar",
    },
  },
  present: {
    yap: {
      1: "yaparım",
      2: "yaparsın",
      3: "yapar",
      11: "yaparız",
      12: "yaparsınız",
      13: "yaparlar",
    },
    ver: {
      1: "veririm",
      2: "verirsin",
      3: "verir",
      11: "veririz",
      12: "verirsiniz",
      13: "verirler",
    },
    dur: {
      1: "dururum",
      2: "durursun",
      3: "durur",
      11: "dururuz",
      12: "durursunuz",
      13: "dururlar",
    },
    bak: {
      1: "bakarım",
      2: "bakarsın",
      3: "bakar",
      11: "bakarız",
      12: "bakarsınız",
      13: "bakarlar",
    },
    gör: {
      1: "görürüm",
      2: "görürsün",
      3: "görür",
      11: "görürüz",
      12: "görürsünüz",
      13: "görürler",
    },
    al: {
      1: "alırım",
      2: "alırsın",
      3: "alır",
      11: "alırız",
      12: "alırsınız",
      13: "alırlar",
    },
    sev: {
      1: "severim",
      2: "seversin",
      3: "sever",
      11: "severiz",
      12: "seversiniz",
      13: "severler",
    },
    geç: {
      1: "geçerim",
      2: "geçersin",
      3: "geçer",
      11: "geçeriz",
      12: "geçersiniz",
      13: "geçerler",
    },
    bil: {
      1: "bilirim",
      2: "bilirsin",
      3: "bilir",
      11: "biliriz",
      12: "bilirsiniz",
      13: "bilirler",
    },
    söyle: {
      1: "söylerim",
      2: "söylersin",
      3: "söyler",
      11: "söyleriz",
      12: "söylersiniz",
      13: "söylerler",
    },
    başla: {
      1: "başlarım",
      2: "başlarsın",
      3: "başlar",
      11: "başlarız",
      12: "başlarsınız",
      13: "başlarlar",
    },
    düşün: {
      1: "düşünürüm",
      2: "düşünürsün",
      3: "düşünür",
      11: "düşünürüz",
      12: "düşünürsünüz",
      13: "düşünürler",
    },
    oku: {
      1: "okurum",
      2: "okursun",
      3: "okur",
      11: "okuruz",
      12: "okursunuz",
      13: "okurlar",
    },
    bul: {
      1: "bulurum",
      2: "bulursun",
      3: "bulur",
      11: "buluruz",
      12: "bulursunuz",
      13: "bulurlar",
    },
    çık: {
      1: "çıkarım",
      2: "çıkarsın",
      3: "çıkar",
      11: "çıkarız",
      12: "çıkarsınız",
      13: "çıkarlar",
    },
  },
  continiuous: {
    yap: {
      1: "yapıyorum",
      2: "yapıyorsun",
      3: "yapıyor",
      11: "yapıyoruz",
      12: "yapıyorsunuz",
      13: "yapıyorlar",
    },
    ver: {
      1: "veriyorum",
      2: "veriyorsun",
      3: "veriyor",
      11: "veriyoruz",
      12: "veriyorsunuz",
      13: "veriyorlar",
    },
    dur: {
      1: "duruyorum",
      2: "duruyorsun",
      3: "duruyor",
      11: "duruyoruz",
      12: "duruyorsunuz",
      13: "duruyorlar",
    },
    bak: {
      1: "bakıyorum",
      2: "bakıyorsun",
      3: "bakıyor",
      11: "bakıyoruz",
      12: "bakıyorsunuz",
      13: "bakıyorlar",
    },
    gör: {
      1: "görüyorum",
      2: "görüyorsun",
      3: "görüyor",
      11: "görüyoruz",
      12: "görüyorsunuz",
      13: "görüyorlar",
    },
    al: {
      1: "alıyorum",
      2: "alıyorsun",
      3: "alıyor",
      11: "alıyoruz",
      12: "alıyorsunuz",
      13: "alıyorlar",
    },
    sev: {
      1: "seviyorum",
      2: "seviyorsun",
      3: "seviyor",
      11: "seviyoruz",
      12: "seviyorsunuz",
      13: "seviyorlar",
    },
    geç: {
      1: "geçiyorum",
      2: "geçiyorsun",
      3: "geçiyor",
      11: "geçiyoruz",
      12: "geçiyorsunuz",
      13: "geçiyorlar",
    },
    bil: {
      1: "biliyorum",
      2: "biliyorsun",
      3: "biliyor",
      11: "biliyoruz",
      12: "biliyorsunuz",
      13: "biliyorlar",
    },
    söyle: {
      1: "söylüyorum",
      2: "söylüyorsun",
      3: "söylüyor",
      11: "söylüyoruz",
      12: "söylüyorsunuz",
      13: "söylüyorlar",
    },
    başla: {
      1: "başlıyorum",
      2: "başlıyorsun",
      3: "başlıyor",
      11: "başlıyoruz",
      12: "başlıyorsunuz",
      13: "başlıyorlar",
    },
    düşün: {
      1: "düşünüyorum",
      2: "düşünüyorsun",
      3: "düşünüyor",
      11: "düşünüyoruz",
      12: "düşünüyorsunuz",
      13: "düşünüyorlar",
    },
    oku: {
      1: "okuyorum",
      2: "okuyorsun",
      3: "okuyor",
      11: "okuyoruz",
      12: "okuyorsunuz",
      13: "okuyorlar",
    },
    bul: {
      1: "buluyorum",
      2: "buluyorsun",
      3: "buluyor",
      11: "buluyoruz",
      12: "buluyorsunuz",
      13: "buluyorlar",
    },
    çık: {
      1: "çıkıyorum",
      2: "çıkıyorsun",
      3: "çıkıyor",
      11: "çıkıyoruz",
      12: "çıkıyorsunuz",
      13: "çıkıyorlar",
    },
  },
  future: {
    yap: {
      1: "yapacağım",
      2: "yapacaksın",
      3: "yapacak",
      11: "yapacağız",
      12: "yapacaksınız",
      13: "yapacaklar",
    },
    ver: {
      1: "vereceğim",
      2: "vereceksin",
      3: "verecek",
      11: "vereceğiz",
      12: "vereceksiniz",
      13: "verecekler",
    },
    dur: {
      1: "duracağım",
      2: "duracaksın",
      3: "duracak",
      11: "duracağız",
      12: "duracaksınız",
      13: "duracaklar",
    },
    bak: {
      1: "bakacağım",
      2: "bakacaksın",
      3: "bakacak",
      11: "bakacağız",
      12: "bakacaksınız",
      13: "bakacaklar",
    },
    gör: {
      1: "göreceğim",
      2: "göreceksin",
      3: "görecek",
      11: "göreceğiz",
      12: "göreceksiniz",
      13: "görecekler",
    },
    al: {
      1: "alacağım",
      2: "alacaksın",
      3: "alacak",
      11: "alacağız",
      12: "alacaksınız",
      13: "alacaklar",
    },
    sev: {
      1: "seveceğim",
      2: "seveceksin",
      3: "sevecek",
      11: "seveceğiz",
      12: "seveceksiniz",
      13: "sevecekler",
    },
    geç: {
      1: "geçeceğim",
      2: "geçeceksin",
      3: "geçecek",
      11: "geçeceğiz",
      12: "geçeceksiniz",
      13: "geçecekler",
    },
    bil: {
      1: "bileceğim",
      2: "bileceksin",
      3: "bilecek",
      11: "bileceğiz",
      12: "bileceksiniz",
      13: "bilecekler",
    },
    söyle: {
      1: "söyleyeceğim",
      2: "söyleyeceksin",
      3: "söyleyecek",
      11: "söyleyeceğiz",
      12: "söyleyeceksiniz",
      13: "söyleyecekler",
    },
    başla: {
      1: "başlayacağım",
      2: "başlayacaksın",
      3: "başlayacak",
      11: "başlayacağız",
      12: "başlayacaksınız",
      13: "başlayacaklar",
    },
    düşün: {
      1: "düşüneceğim",
      2: "düşüneceksin",
      3: "düşünecek",
      11: "düşüneceğiz",
      12: "düşüneceksiniz",
      13: "düşünecekler",
    },
    oku: {
      1: "okuyacağım",
      2: "okuyacaksın",
      3: "okuyacak",
      11: "okuyacağız",
      12: "okuyacaksınız",
      13: "okuyacaklar",
    },
    bul: {
      1: "bulacağım",
      2: "bulacaksın",
      3: "bulacak",
      11: "bulacağız",
      12: "bulacaksınız",
      13: "bulacaklar",
    },
    çık: {
      1: "çıkacağım",
      2: "çıkacaksın",
      3: "çıkacak",
      11: "çıkacağız",
      12: "çıkacaksınız",
      13: "çıkacaklar",
    },
  },
  optative: {
    yap: {
      1: "yapayım",
      2: "yapasın",
      3: "yapa",
      11: "yapalım",
      12: "yapasınız",
      13: "yapalar",
    },
    ver: {
      1: "vereyim",
      2: "veresin",
      3: "vere",
      11: "verelim",
      12: "veresiniz",
      13: "vereler",
    },
    dur: {
      1: "durayım",
      2: "durasın",
      3: "dura",
      11: "duralım",
      12: "durasınız",
      13: "duralar",
    },
    bak: {
      1: "bakayım",
      2: "bakasın",
      3: "baka",
      11: "bakalım",
      12: "bakasınız",
      13: "bakalar",
    },
    gör: {
      1: "göreyim",
      2: "göresin",
      3: "göre",
      11: "görelim",
      12: "göresiniz",
      13: "göreler",
    },
    al: {
      1: "alayım",
      2: "alasın",
      3: "ala",
      11: "alalım",
      12: "alasınız",
      13: "alalar",
    },
    sev: {
      1: "seveyim",
      2: "sevesin",
      3: "seve",
      11: "sevelim",
      12: "sevesiniz",
      13: "seveler",
    },
    geç: {
      1: "geçeyim",
      2: "geçesin",
      3: "geçe",
      11: "geçelim",
      12: "geçesiniz",
      13: "geçeler",
    },
    bil: {
      1: "bileyim",
      2: "bilesin",
      3: "bile",
      11: "bilelim",
      12: "bilesiniz",
      13: "bileler",
    },
    söyle: {
      1: "söyleyeyim",
      2: "söyleyesin",
      3: "söyleye",
      11: "söyleyelim",
      12: "söyleyesiniz",
      13: "söyleyeler",
    },
    başla: {
      1: "başlayayım",
      2: "başlayasın",
      3: "başlaya",
      11: "başlayalım",
      12: "başlayasınız",
      13: "başlayalar",
    },
    düşün: {
      1: "düşüneyim",
      2: "düşünesin",
      3: "düşüne",
      11: "düşünelim",
      12: "düşünesiniz",
      13: "düşüneler",
    },
    oku: {
      1: "okuyayım",
      2: "okuyasın",
      3: "okuya",
      11: "okuyalım",
      12: "okuyasınız",
      13: "okuyalar",
    },
    bul: {
      1: "bulayım",
      2: "bulasın",
      3: "bula",
      11: "bulalım",
      12: "bulasınız",
      13: "bulalar",
    },
    çık: {
      1: "çıkayım",
      2: "çıkasın",
      3: "çıka",
      11: "çıkalım",
      12: "çıkasınız",
      13: "çıkalar",
    },
  },
  conditional: {
    yap: {
      1: "yapsam",
      2: "yapsan",
      3: "yapsa",
      11: "yapsak",
      12: "yapsanız",
      13: "yapsalar",
    },
    ver: {
      1: "versem",
      2: "versen",
      3: "verse",
      11: "versek",
      12: "verseniz",
      13: "verseler",
    },
    dur: {
      1: "dursam",
      2: "dursan",
      3: "dursa",
      11: "dursak",
      12: "dursanız",
      13: "dursalar",
    },
    bak: {
      1: "baksam",
      2: "baksan",
      3: "baksa",
      11: "baksak",
      12: "baksanız",
      13: "baksalar",
    },
    gör: {
      1: "görsem",
      2: "görsen",
      3: "görse",
      11: "görsek",
      12: "görseniz",
      13: "görseler",
    },
    al: {
      1: "alsam",
      2: "alsan",
      3: "alsa",
      11: "alsak",
      12: "alsanız",
      13: "alsalar",
    },
    sev: {
      1: "sevsem",
      2: "sevsen",
      3: "sevse",
      11: "sevsek",
      12: "sevseniz",
      13: "sevseler",
    },
    geç: {
      1: "geçsem",
      2: "geçsen",
      3: "geçse",
      11: "geçsek",
      12: "geçseniz",
      13: "geçseler",
    },
    bil: {
      1: "bilsem",
      2: "bilsen",
      3: "bilse",
      11: "bilsek",
      12: "bilseniz",
      13: "bilseler",
    },
    söyle: {
      1: "söylesem",
      2: "söylesen",
      3: "söylese",
      11: "söylesek",
      12: "söyleseniz",
      13: "söyleseler",
    },
    başla: {
      1: "başlasam",
      2: "başlasan",
      3: "başlasa",
      11: "başlasak",
      12: "başlasanız",
      13: "başlasalar",
    },
    düşün: {
      1: "düşünsem",
      2: "düşünsen",
      3: "düşünse",
      11: "düşünsek",
      12: "düşünseniz",
      13: "düşünseler",
    },
    oku: {
      1: "okusam",
      2: "okusan",
      3: "okusa",
      11: "okusak",
      12: "okusanız",
      13: "okusalar",
    },
    bul: {
      1: "bulsam",
      2: "bulsan",
      3: "bulsa",
      11: "bulsak",
      12: "bulsanız",
      13: "bulsalar",
    },
    çık: {
      1: "çıksam",
      2: "çıksan",
      3: "çıksa",
      11: "çıksak",
      12: "çıksanız",
      13: "çıksalar",
    },
  },
  necessitate: {
    yap: {
      1: "yapmalıyım",
      2: "yapmalısın",
      3: "yapmalı",
      11: "yapmalıyız",
      12: "yapmalısınız",
      13: "yapmalılar",
    },
    ver: {
      1: "vermeliyim",
      2: "vermelisin",
      3: "vermeli",
      11: "vermeliyiz",
      12: "vermelisiniz",
      13: "vermeliler",
    },
    dur: {
      1: "durmalıyız",
      2: "durmalısın",
      3: "durmalı",
      11: "durmalıyız",
      12: "durmalısınz",
      13: "durmalılar",
    },
    bak: {
      1: "bakmalıyım",
      2: "bakmalısın",
      3: "bakmalı",
      11: "bakmalıyız",
      12: "bakmalısınız",
      13: "bakmalılar",
    },
    gör: {
      1: "görmeliyim",
      2: "görmelisin",
      3: "görmeli",
      11: "görmeliyiz",
      12: "görmelisiniz",
      13: "görmeliler",
    },
    al: {
      1: "almalıyım",
      2: "almalısın",
      3: "almalı",
      11: "almalıyız",
      12: "almalısınız",
      13: "almalılar",
    },
    sev: {
      1: "sevmeliyim",
      2: "sevmelisin",
      3: "sevmeli",
      11: "sevmeliyiz",
      12: "sevmelisiniz",
      13: "sevmeliler",
    },
    geç: {
      1: "geçmeliyim",
      2: "geçmelisin",
      3: "geçmeli",
      11: "geçmeliyiz",
      12: "geçmelisiniz",
      13: "geçmeliler",
    },
    bil: {
      1: "bilmeliyim",
      2: "bilmelisin",
      3: "bilmeli",
      11: "bilmeliyiz",
      12: "bilmelisiniz",
      13: "bilmeliler",
    },
    söyle: {
      1: "söylemeliyim",
      2: "söylemelisin",
      3: "söylemeli",
      11: "söylemeliyiz",
      12: "söylemelisiniz",
      13: "söylemeliler",
    },
    başla: {
      1: "başlamalıyım",
      2: "başlamalısın",
      3: "başlamalı",
      11: "başlamalıyız",
      12: "başlamalısınız",
      13: "başlamalılar",
    },
    düşün: {
      1: "düşünmeliyim",
      2: "düşünmelisin",
      3: "düşünmeli",
      11: "düşünmeliyiz",
      12: "düşünmelisiniz",
      13: "düşünmeliler",
    },
    oku: {
      1: "okumalıyım",
      2: "okumalısın",
      3: "okumalı",
      11: "okumalıyız",
      12: "okumalısınız",
      13: "okumalılar",
    },
    bul: {
      1: "bulmalıyım",
      2: "bulmalısın",
      3: "bulmalı",
      11: "bulmalıyız",
      12: "bulmalısınız",
      13: "bulmalılar",
    },
    çık: {
      1: "çıkmalıyım",
      2: "çıkmalısın",
      3: "çıkmalı",
      11: "çıkmalıyız",
      12: "çıkmalısınız",
      13: "çıkmalılar",
    },
  },
  imperative: {
    yap: {
      2: "yap",
      3: "yapsın",
      12: "yapın",
      13: "yapsınlar",
    },
    ver: {
      2: "ver",
      3: "versin",
      12: "verin",
      13: "versinler",
    },
    dur: {
      2: "dur",
      3: "dursun",
      12: "durun",
      13: "dursunlar",
    },
    bak: {
      2: "bak",
      3: "baksın",
      12: "bakın",
      13: "baksınlar",
    },
    gör: {
      2: "gör",
      3: "görsün",
      12: "görün",
      13: "görsünler",
    },
    al: {
      2: "al",
      3: "alsın",
      12: "alın",
      13: "alsınlar",
    },
    sev: {
      2: "sev",
      3: "sevsin",
      12: "sevin",
      13: "sevsinler",
    },
    geç: {
      2: "geç",
      3: "geçsin",
      12: "geçin",
      13: "geçsinler",
    },
    bil: {
      2: "bil",
      3: "bilsin",
      12: "bilin",
      13: "bilsinler",
    },
    söyle: {
      2: "söyle",
      3: "söylesin",
      12: "söyleyin",
      13: "söylesinler",
    },
    başla: {
      2: "başla",
      3: "başlasın",
      12: "başlayın",
      13: "başlasınlar",
    },
    düşün: {
      2: "düşün",
      3: "düşünsün",
      12: "düşünün",
      13: "düşünsünler",
    },
    oku: {
      2: "oku",
      3: "okusun",
      12: "okuyun",
      13: "okusunlar",
    },
    bul: {
      2: "bul",
      3: "bulsun",
      12: "bulun",
      13: "bulsunlar",
    },
    çık: {
      2: "çık",
      3: "çıksın",
      12: "çıkın",
      13: "çıksınlar",
    },
  },
};

export const persons = [1, 2, 3, 11, 12, 13];
export const imperativePersons = [2, 3, 12, 13];
export const coordination = {
  1: "Birinci Tekil Şahıs",
  2: "İkinci Tekil Şahıs",
  3: "Üçüncü Tekil Şahıs",
  11: "Birinci Çoğul Şahıs",
  12: "İkinci Çoğul Şahıs",
  13: "Üçüncü Çoğul Şahıs",

  "Geçmiş Zaman": "past",
  "Duyulan Geçmiş Zaman": "pastV2",
  "Geniş Zaman": "present",
  "Şimdiki Zaman": "continiuous",
  "Gelecek Zaman": "future",
  "Istek Kipi": "optative",
  "Dilek Kipi": "conditional",
  "Gereklilik Kipi": "necessitate",
  "Emir Kipi": "imperative",
};

export const modes = [
  "Geçmiş Zaman",
  "Duyulan Geçmiş Zaman",
  "Geniş Zaman",
  "Şimdiki Zaman",
  "Gelecek Zaman",
  "Istek Kipi",
  "Dilek Kipi",
  "Gereklilik Kipi",
  "Emir Kipi",
];
export const stems = [
  "yap",
  "ver",
  "dur",
  "bak",
  "gör",
  "al",
  "sev",
  "geç",
  "bil",
  "söyle",
  "başla",
  "düşün",
  "oku",
  "bul",
  "çık",
];

export const random = (array) => {
  return array[Math.floor(Math.random() * array.length)];
};
