export const conjugations = {
  past: {
    yap: {
      1: "yaptım",
      2: "yaptın",
      3: "yaptı",
      11: "yaptık",
      12: "yaptınız",
      13: "yaptılar",
    },
    ver: {
      1: "verdim",
      2: "verdin",
      3: "verdi",
      11: "verdik",
      12: "verdiniz",
      13: "verdiler",
    },
    dur: {
      1: "durdum",
      2: "durdun",
      3: "durdu",
      11: "durduk",
      12: "durdunuz",
      13: "durdular",
    },
    sık: {
      1: "sıktım",
      2: "sıktın",
      3: "sıktı",
      11: "sıktık",
      12: "sıktınız",
      13: "sıktılar",
    },
    bak: {
      1: "baktım",
      2: "baktın",
      3: "baktı",
      11: "baktık",
      12: "baktınız",
      13: "baktılar",
    },
    gör: {
      1: "gördüm",
      2: "gördün",
      3: "gördü",
      11: "gördük",
      12: "gördünüz",
      13: "gördüler",
    },
    al: {
      1: "aldım",
      2: "aldın",
      3: "aldı",
      11: "aldık",
      12: "aldınız",
      13: "aldılar",
    },
    sev: {
      1: "sevdim",
      2: "sevdin",
      3: "sevdi",
      11: "sevdik",
      12: "sevdiniz",
      13: "sevdiler",
    },
    geç: {
      1: "geçtim",
      2: "geçtin",
      3: "geçti",
      11: "geçtik",
      12: "geçtiniz",
      13: "geçtiler",
    },
  },
  pastV2: {
    yap: {
      1: "yapmışım",
      2: "yapmışsın",
      3: "yapmış",
      11: "yapmışız",
      12: "yapmışsınız",
      13: "yapmışlar",
    },
    ver: {
      1: "vermişim",
      2: "vermişsin",
      3: "vermiş",
      11: "vermişiz",
      12: "vermişsiniz",
      13: "vermişler",
    },
    dur: {
      1: "durmuşum",
      2: "durmuşsun",
      3: "durmuş",
      11: "durmuşuz",
      12: "durmuşsunuz",
      13: "durmuşlar",
    },
    sık: {
      1: "sıkmışım",
      2: "sıkmışsın",
      3: "sıkmış",
      11: "sıkmışız",
      12: "sıkmışsınız",
      13: "sıkmışlar",
    },
    bak: {
      1: "bakmışım",
      2: "bakmışsın",
      3: "bakmış",
      11: "bakmışız",
      12: "bakmışsınız",
      13: "bakmışlar",
    },
    gör: {
      1: "görmüşüm",
      2: "görmüşsün",
      3: "görmüş",
      11: "görmüşüz",
      12: "görmüşsünüz",
      13: "görmüşler",
    },
    al: {
      1: "almışım",
      2: "almışsın",
      3: "almış",
      11: "almışız",
      12: "almışsınız",
      13: "almışlar",
    },
    sev: {
      1: "sevmişim",
      2: "sevmişsin",
      3: "sevmiş",
      11: "sevmişiz",
      12: "sevmişsiniz",
      13: "sevmişler",
    },
    geç: {
      1: "geçmişim",
      2: "geçmişsin",
      3: "geçmiş",
      11: "geçmişiz",
      12: "geçmişsiniz",
      13: "geçmişler",
    },
  },
  present: {
    yap: {
      1: "yaparım",
      2: "yaparsın",
      3: "yapar",
      11: "yaparız",
      12: "yaparsınız",
      13: "yaparlar",
    },
    ver: {
      1: "veririm",
      2: "verirsin",
      3: "verir",
      11: "veririz",
      12: "verirsiniz",
      13: "verirler",
    },
    dur: {
      1: "dururum",
      2: "durursun",
      3: "durur",
      11: "dururuz",
      12: "durursunuz",
      13: "dururlar",
    },
    sık: {
      1: "sıkarım",
      2: "sıkarsın",
      3: "sıkar",
      11: "sıkarız",
      12: "sıkarsınız",
      13: "sıkarlar",
    },
    bak: {
      1: "bakarım",
      2: "bakarsın",
      3: "bakar",
      11: "bakarız",
      12: "bakarsınız",
      13: "bakarlar",
    },
    gör: {
      1: "görürüm",
      2: "görürsün",
      3: "görür",
      11: "görürüz",
      12: "görürsünüz",
      13: "görürler",
    },
    al: {
      1: "alırım",
      2: "alırsın",
      3: "alır",
      11: "alırız",
      12: "alırsınız",
      13: "alırlar",
    },
    sev: {
      1: "severim",
      2: "seversin",
      3: "sever",
      11: "severiz",
      12: "seversiniz",
      13: "severler",
    },
    geç: {
      1: "geçerim",
      2: "geçersin",
      3: "geçer",
      11: "geçeriz",
      12: "geçersiniz",
      13: "geçerler",
    },
  },
  continiuous: {
    yap: {
      1: "yapıyorum",
      2: "yapıyorsun",
      3: "yapıyor",
      11: "yapıyoruz",
      12: "yapıyorsunuz",
      13: "yapıyorlar",
    },
    ver: {
      1: "veriyorum",
      2: "veriyorsun",
      3: "veriyor",
      11: "veriyoruz",
      12: "veriyorsunuz",
      13: "veriyorlar",
    },
    dur: {
      1: "duruyorum",
      2: "duruyorsun",
      3: "duruyor",
      11: "duruyoruz",
      12: "duruyorsunuz",
      13: "duruyorlar",
    },
    sık: {
      1: "sıkıyorum",
      2: "sıkıyorsun",
      3: "sıkıyor",
      11: "sıkıyoruz",
      12: "sıkıyorsunuz",
      13: "sıkıyorlar",
    },
    bak: {
      1: "bakıyorum",
      2: "bakıyorsun",
      3: "bakıyor",
      11: "bakıyoruz",
      12: "bakıyorsunuz",
      13: "bakıyorlar",
    },
    gör: {
      1: "görüyorum",
      2: "görüyorsun",
      3: "görüyor",
      11: "görüyoruz",
      12: "görüyorsunuz",
      13: "görüyorlar",
    },
    al: {
      1: "alıyorum",
      2: "alıyorsun",
      3: "alıyor",
      11: "alıyoruz",
      12: "alıyorsunuz",
      13: "alıyorlar",
    },
    sev: {
      1: "seviyorum",
      2: "seviyorsun",
      3: "seviyor",
      11: "seviyoruz",
      12: "seviyorsunuz",
      13: "seviyorlar",
    },
    geç: {
      1: "geçiyorum",
      2: "geçiyorsun",
      3: "geçiyor",
      11: "geçiyoruz",
      12: "geçiyorsunuz",
      13: "geçiyorlar",
    },
  },
  future: {
    yap: {
      1: "yapacağım",
      2: "yapacaksın",
      3: "yapacak",
      11: "yapacağız",
      12: "yapacaksınız",
      13: "yapacaklar",
    },
    ver: {
      1: "vereceğim",
      2: "vereceksin",
      3: "verecek",
      11: "vereceğiz",
      12: "vereceksiniz",
      13: "verecekler",
    },
    dur: {
      1: "duracağım",
      2: "duracaksın",
      3: "duracak",
      11: "duracağız",
      12: "duracaksınız",
      13: "duracaklar",
    },
    sık: {
      1: "sıkacağım",
      2: "sıkacaksın",
      3: "sıkacak",
      11: "sıkacağız",
      12: "sıkacaksınız",
      13: "sıkacaklar",
    },
    bak: {
      1: "bakacağım",
      2: "bakacaksın",
      3: "bakacak",
      11: "bakacağız",
      12: "bakacaksınız",
      13: "bakacaklar",
    },
    gör: {
      1: "göreceğim",
      2: "göreceksin",
      3: "görecek",
      11: "göreceğiz",
      12: "göreceksiniz",
      13: "görecekler",
    },
    al: {
      1: "alacağım",
      2: "alacaksın",
      3: "alacak",
      11: "alacağız",
      12: "alacaksınız",
      13: "alacaklar",
    },
    sev: {
      1: "seveceğim",
      2: "seveceksin",
      3: "sevecek",
      11: "seveceğiz",
      12: "seveceksiniz",
      13: "sevecekler",
    },
    geç: {
      1: "geçeceğim",
      2: "geçeceksin",
      3: "geçecek",
      11: "geçeceğiz",
      12: "geçeceğiz",
      13: "geçecekler",
    },
  },
  optative: {
    yap: {
      1: "yapayım",
      2: "yapasın",
      3: "yapa",
      11: "yapalım",
      12: "yapasınız",
      13: "yapalar",
    },
    ver: {
      1: "vereyim",
      2: "veresin",
      3: "vere",
      11: "verelim",
      12: "veresiniz",
      13: "vereler",
    },
    dur: {
      1: "durayım",
      2: "durasın",
      3: "dura",
      11: "duralım",
      12: "durasınız",
      13: "duralar",
    },
    sık: {
      1: "sıkayım",
      2: "sıkasın",
      3: "sıka",
      11: "sıkalım",
      12: "sıkasınız",
      13: "sıkalar",
    },
    bak: {
      1: "bakayım",
      2: "bakasın",
      3: "baka",
      11: "bakalım",
      12: "bakasınız",
      13: "bakalar",
    },
    gör: {
      1: "göreyim",
      2: "göresin",
      3: "göre",
      11: "görelim",
      12: "göresiniz",
      13: "göreler",
    },
    al: {
      1: "alayım",
      2: "alasın",
      3: "ala",
      11: "alalım",
      12: "alasınız",
      13: "alalar",
    },
    sev: {
      1: "seveyim",
      2: "sevesin",
      3: "seve",
      11: "sevelim",
      12: "sevesiniz",
      13: "seveler",
    },
    geç: {
      1: "geçeyim",
      2: "geçesin",
      3: "geçe",
      11: "geçelim",
      12: "geçesiniz",
      13: "geçeler",
    },
  },
  conditional: {
    yap: {
      1: "yapsam",
      2: "yapsan",
      3: "yapsa",
      11: "yapsak",
      12: "yapsanız",
      13: "yapsalar",
    },
    ver: {
      1: "versem",
      2: "versen",
      3: "verse",
      11: "versek",
      12: "verseniz",
      13: "verseler",
    },
    dur: {
      1: "dursam",
      2: "dursan",
      3: "dursa",
      11: "dursak",
      12: "dursanız",
      13: "dursalar",
    },
    sık: {
      1: "sıksam",
      2: "sıksan",
      3: "sıksa",
      11: "sıksak",
      12: "sıksanız",
      13: "sıksalar",
    },
    bak: {
      1: "baksam",
      2: "baksan",
      3: "baksa",
      11: "baksak",
      12: "baksanız",
      13: "baksalar",
    },
    gör: {
      1: "görsem",
      2: "görsen",
      3: "görse",
      11: "görsek",
      12: "görseniz",
      13: "görseler",
    },
    al: {
      1: "alsam",
      2: "alsan",
      3: "alsa",
      11: "alsak",
      12: "alsanız",
      13: "alsalar",
    },
    sev: {
      1: "sevsem",
      2: "sevsen",
      3: "sevse",
      11: "sevsek",
      12: "sevseniz",
      13: "sevseler",
    },
    geç: {
      1: "geçsem",
      2: "geçsen",
      3: "geçse",
      11: "geçsek",
      12: "geçseniz",
      13: "geçseler",
    },
  },
  necessitate: {
    yap: {
      1: "yapmalıyım",
      2: "yapmalısın",
      3: "yapmalı",
      11: "yapmalıyız",
      12: "yapmalısınız",
      13: "yapmalılar",
    },
    ver: {
      1: "vermeliyim",
      2: "vermelisin",
      3: "vermeli",
      11: "vermeliyiz",
      12: "vermelisiniz",
      13: "vermeliler",
    },
    dur: {
      1: "durmalıyız",
      2: "durmalısın",
      3: "durmalı",
      11: "durmalıyız",
      12: "durmalısınz",
      13: "durmalılar",
    },
    sık: {
      1: "sıkmalıyız",
      2: "sıkmalısın",
      3: "sıkmalı",
      11: "sıkmalıyız",
      12: "sıkmalısınz",
      13: "sıkmalılar",
    },
    bak: {
      1: "bakmalıyım",
      2: "bakmalısın",
      3: "bakmalı",
      11: "bakmalıyız",
      12: "bakmalısınız",
      13: "bakmalılar",
    },
    gör: {
      1: "görmeliyim",
      2: "görmelisin",
      3: "görmeli",
      11: "görmeliyiz",
      12: "görmelisiniz",
      13: "görmeliler",
    },
    al: {
      1: "almalıyım",
      2: "almalısın",
      3: "almalı",
      11: "almalıyız",
      12: "almalısınız",
      13: "almalılar",
    },
    sev: {
      1: "sevmeliyim",
      2: "sevmelisin",
      3: "sevmeli",
      11: "sevmeliyiz",
      12: "sevmelisiniz",
      13: "sevmeliler",
    },
    geç: {
      1: "geçmeliyim",
      2: "geçmelisin",
      3: "geçmeli",
      11: "geçmeliyiz",
      12: "geçmelisiniz",
      13: "geçmeliler",
    },
  },
  imperative: {
    yap: {
      2: "yap",
      3: "yapsın",
      12: "yapın",
      13: "yapsınlar",
    },
    ver: {
      2: "ver",
      3: "versin",
      12: "verin",
      13: "versinler",
    },
    dur: {
      2: "dur",
      3: "dursun",
      12: "durun",
      13: "dursunlar",
    },
    sık: {
      2: "sık",
      3: "sıksın",
      12: "sıkın",
      13: "sıksınlar",
    },
    bak: {
      2: "bak",
      3: "baksın",
      12: "bakın",
      13: "baksınlar",
    },
    gör: {
      2: "gör",
      3: "görsün",
      12: "görün",
      13: "görsünler",
    },
    al: {
      2: "al",
      3: "alsın",
      12: "alın",
      13: "alsınlar",
    },
    sev: {
      2: "sev",
      3: "sevsin",
      12: "sevin",
      13: "sevsinler",
    },
    geç: {
      2: "geç",
      3: "geçsin",
      12: "geçin",
      13: "geçsinler",
    },
  },
};

export const persons = [1, 2, 3, 11, 12, 13];
export const coordination = {
  1: "Birinci Tekil Şahıs",
  2: "İkinci Tekil Şahıs",
  3: "Üçüncü Tekil Şahıs",
  11: "Birinci Çoğul Şahıs",
  12: "İkinci Çoğul Şahıs",
  13: "Üçüncü Çoğul Şahıs",

  "Geçmiş Zaman": "past",
  "Duyulan Geçmiş Zaman": "pastV2",
  "Geniş Zaman": "present",
  "Şimdiki Zaman": "continiuous",
  "Gelecek Zaman": "future",
  "Istek Kipi": "optative",
  "Dilek Kipi": "conditional",
  "Gereklilik Kipi": "necessitate",
  "Emir Kipi": "imperative",
};

export const modes = [
  "Geçmiş Zaman",
  "Duyulan Geçmiş Zaman",
  "Geniş Zaman",
  "Şimdiki Zaman",
  "Gelecek Zaman",
  "Istek Kipi",
  "Dilek Kipi",
  "Gereklilik Kipi",
  "Emir Kipi",
];
export const stems = [
  "yap",
  "ver",
  "dur",
  "sık",
  "bak",
  "gör",
  "al",
  "sev",
  "geç",
];

export const random = (array) => {
  return array[Math.floor(Math.random() * array.length)];
};
